## Linear Algebra

In [1]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

A = np.random.rand(3, 3)
B = np.random.rand(3, 5)

In [4]:
# Transpose
print(B)
print(B.transpose())

[[0.04107541 0.42537068 0.97933564 0.09782949 0.42058076]
 [0.3626133  0.09704268 0.67490471 0.05545207 0.54328634]
 [0.22294954 0.15586483 0.4383283  0.53108622 0.21011585]]
[[0.04107541 0.3626133  0.22294954]
 [0.42537068 0.09704268 0.15586483]
 [0.97933564 0.67490471 0.4383283 ]
 [0.09782949 0.05545207 0.53108622]
 [0.42058076 0.54328634 0.21011585]]


In [11]:
# Addition / Substraction
print(x + y)
print(x - y)

[5 7 9]
[-3 -3 -3]


In [20]:
# Multiplication
np.dot(A, x)

array([3.11212873, 1.46021092, 4.14555591])

In [21]:
res = 0
for i in range(3):
    res = res + A[0, i] * x[i]
print(res)

3.112128725756909


In [25]:
np.dot(A, B)

array([[0.83226318, 0.83927654, 0.69781026, 0.10176759, 0.38694018],
       [1.02246745, 1.13950673, 1.02356013, 0.5332835 , 1.03946706],
       [0.04933927, 0.16939824, 0.17710723, 0.22036344, 0.39464019]])

Matrix multiplication is not commutative!

In [5]:
A = np.random.randn(2, 2)
B = np.random.randn(2, 2)

print(A @ B)
print(B @ A)


[[-1.2249778   2.19351458]
 [-0.96738985 -0.3278361 ]]
[[-2.77075123 -5.64677545]
 [ 1.04452127  1.21793734]]


In [30]:
# Inverse
np.linalg.inv(A)

array([[-4.54973122e-03, -4.12805865e-02,  1.39859357e+00],
       [-5.45866397e+00,  5.00437775e+00, -5.42016641e+00],
       [ 1.24291286e+00, -4.82724957e-02,  1.02077334e-03]])